const countryMeta = {
  Afghanistan: { emoji: "🇦🇫" },
  Albania: { emoji: "🇦🇱" },
  Algeria: { emoji: "🇩🇿" },
  Andorra: { emoji: "🇦🇩" },
  Angola: { emoji: "🇦🇴" },
  "Antigua and Barbuda": { emoji: "🇦🇬" },
  Argentina: { emoji: "🇦🇷" },
  Armenia: { emoji: "🇦🇲" },
  Australia: { emoji: "🇦🇺" },
  Austria: { emoji: "🇦🇹" },
  Azerbaijan: { emoji: "🇦🇿" },
  Bahamas: { emoji: "🇧🇸" },
  Bahrain: { emoji: "🇧🇭" },
  Bangladesh: { emoji: "🇧🇩" },
  Barbados: { emoji: "🇧🇧" },
  Belarus: { emoji: "🇧🇾" },
  Belgium: { emoji: "🇧🇪" },
  Belize: { emoji: "🇧🇿" },
  Benin: { emoji: "🇧🇯" },
  Bhutan: { emoji: "🇧🇹" },
  Bolivia: { emoji: "🇧🇴" },
  "Bosnia and Herzegovina": { emoji: "🇧🇦" },
  Botswana: { emoji: "🇧🇼" },
  Brazil: { emoji: "🇧🇷" },
  Brunei: { emoji: "🇧🇳" },
  Bulgaria: { emoji: "🇧🇬" },
  "Burkina Faso": { emoji: "🇧🇫" },
  Burundi: { emoji: "🇧🇮" },
  "Cape Verde": { emoji: "🇨🇻" },
  Cambodia: { emoji: "🇰🇭" },
  Cameroon: { emoji: "🇨🇲" },
  Canada: { emoji: "🇨🇦" },
  "Central African Republic": { emoji: "🇨🇫" },
  Chad: { emoji: "🇹🇩" },
  Chile: { emoji: "🇨🇱" },
  China: { emoji: "🇨🇳" },
  Colombia: { emoji: "🇨🇴" },
  Comoros: { emoji: "🇰🇲" },
  "Republic of the Congo": { emoji: "🇨🇬" },
  "Democratic Republic of the Congo": { emoji: "🇨🇩" },
  "Costa Rica": { emoji: "🇨🇷" },
  "Côte d'Ivoire": { emoji: "🇨🇮" },
  Croatia: { emoji: "🇭🇷" },
  Cuba: { emoji: "🇨🇺" },
  Cyprus: { emoji: "🇨🇾" },
  "Czech Republic": { emoji: "🇨🇿" },
  Denmark: { emoji: "🇩🇰" },
  Djibouti: { emoji: "🇩🇯" },
  Dominica: { emoji: "🇩🇲" },
  "Dominican Republic": { emoji: "🇩🇴" },
  Ecuador: { emoji: "🇪🇨" },
  Egypt: { emoji: "🇪🇬" },
  "El Salvador": { emoji: "🇸🇻" },
  "Equatorial Guinea": { emoji: "🇬🇶" },
  Eritrea: { emoji: "🇪🇷" },
  Estonia: { emoji: "🇪🇪" },
  Eswatini: { emoji: "🇸🇿" },
  Ethiopia: { emoji: "🇪🇹" },
  Fiji: { emoji: "🇫🇯" },
  Finland: { emoji: "🇫🇮" },
  France: { emoji: "🇫🇷" },
  Gabon: { emoji: "🇬🇦" },
  Gambia: { emoji: "🇬🇲" },
  Georgia: { emoji: "🇬🇪" },
  Germany: { emoji: "🇩🇪" },
  Ghana: { emoji: "🇬🇭" },
  Greece: { emoji: "🇬🇷" },
  Grenada: { emoji: "🇬🇩" },
  Guatemala: { emoji: "🇬🇹" },
  Guinea: { emoji: "🇬🇳" },
  "Guinea-Bissau": { emoji: "🇬🇼" },
  Guyana: { emoji: "🇬🇾" },
  Haiti: { emoji: "🇭🇹" },
  Honduras: { emoji: "🇭🇳" },
  Hungary: { emoji: "🇭🇺" },
  Iceland: { emoji: "🇮🇸" },
  India: { emoji: "🇮🇳" },
  Indonesia: { emoji: "🇮🇩" },
  Iran: { emoji: "🇮🇷" },
  Iraq: { emoji: "🇮🇶" },
  Ireland: { emoji: "🇮🇪" },
  Israel: { emoji: "🇮🇱" },
  Italy: { emoji: "🇮🇹" },
  Jamaica: { emoji: "🇯🇲" },
  Japan: { emoji: "🇯🇵" },
  Jordan: { emoji: "🇯🇴" },
  Kazakhstan: { emoji: "🇰🇿" },
  Kenya: { emoji: "🇰🇪" },
  Kiribati: { emoji: "🇰🇮" },
  Kuwait: { emoji: "🇰🇼" },
  Kyrgyzstan: { emoji: "🇰🇬" },
  Laos: { emoji: "🇱🇦" },
  Latvia: { emoji: "🇱🇻" },
  Lebanon: { emoji: "🇱🇧" },
  Lesotho: { emoji: "🇱🇸" },
  Liberia: { emoji: "🇱🇷" },
  Libya: { emoji: "🇱🇾" },
  Liechtenstein: { emoji: "🇱🇮" },
  Lithuania: { emoji: "🇱🇹" },
  Luxembourg: { emoji: "🇱🇺" },
  Madagascar: { emoji: "🇲🇬" },
  Malawi: { emoji: "🇲🇼" },
  Malaysia: { emoji: "🇲🇾" },
  Maldives: { emoji: "🇲🇻" },
  Mali: { emoji: "🇲🇱" },
  Malta: { emoji: "🇲🇹" },
  "Marshall Islands": { emoji: "🇲🇭" },
  Mauritania: { emoji: "🇲🇷" },
  Mauritius: { emoji: "🇲🇺" },
  Mexico: { emoji: "🇲🇽" },
  Micronesia: { emoji: "🇫🇲" },
  Moldova: { emoji: "🇲🇩" },
  Monaco: { emoji: "🇲🇨" },
  Mongolia: { emoji: "🇲🇳" },
  Montenegro: { emoji: "🇲🇪" },
  Morocco: { emoji: "🇲🇦" },
  Mozambique: { emoji: "🇲🇿" },
  Myanmar: { emoji: "🇲🇲" },
  Namibia: { emoji: "🇳🇦" },
  Nauru: { emoji: "🇳🇷" },
  Nepal: { emoji: "🇳🇵" },
  Netherlands: { emoji: "🇳🇱" },
  "New Zealand": { emoji: "🇳🇿" },
  Nicaragua: { emoji: "🇳🇮" },
  Niger: { emoji: "🇳🇪" },
  Nigeria: { emoji: "🇳🇬" },
  "North Korea": { emoji: "🇰🇵" },
  "North Macedonia": { emoji: "🇲🇰" },
  Norway: { emoji: "🇳🇴" },
  Oman: { emoji: "🇴🇲" },
  Pakistan: { emoji: "🇵🇰" },
  Palau: { emoji: "🇵🇼" },
  Palestine: { emoji: "🇵🇸" },
  Panama: { emoji: "🇵🇦" },
  "Papua New Guinea": { emoji: "🇵🇬" },
  Paraguay: { emoji: "🇵🇾" },
  Peru: { emoji: "🇵🇪" },
  Philippines: { emoji: "🇵🇭" },
  Poland: { emoji: "🇵🇱" },
  Portugal: { emoji: "🇵🇹" },
  Qatar: { emoji: "🇶🇦" },
  Romania: { emoji: "🇷🇴" },
  Russia: { emoji: "🇷🇺" },
  Rwanda: { emoji: "🇷🇼" },
  "Saint Kitts and Nevis": { emoji: "🇰🇳" },
  "Saint Lucia": { emoji: "🇱🇨" },
  "Saint Vincent and the Grenadines": { emoji: "🇻🇨" },
  Samoa: { emoji: "🇼🇸" },
  "San Marino": { emoji: "🇸🇲" },
  "São Tomé and Príncipe": { emoji: "🇸🇹" },
  "Saudi Arabia": { emoji: "🇸🇦" },
  Senegal: { emoji: "🇸🇳" },
  Serbia: { emoji: "🇷🇸" },
  Seychelles: { emoji: "🇸🇨" },
  "Sierra Leone": { emoji: "🇸🇱" },
  Singapore: { emoji: "🇸🇬" },
  Slovakia: { emoji: "🇸🇰" },
  Slovenia: { emoji: "🇸🇮" },
  "Solomon Islands": { emoji: "🇸🇧" },
  Somalia: { emoji: "🇸🇴" },
  "South Africa": { emoji: "🇿🇦" },
  "South Korea": { emoji: "🇰🇷" },
  "South Sudan": { emoji: "🇸🇸" },
  Spain: { emoji: "🇪🇸" },
  "Sri Lanka": { emoji: "🇱🇰" },
  Sudan: { emoji: "🇸🇩" },
  Suriname: { emoji: "🇸🇷" },
  Sweden: { emoji: "🇸🇪" },
  Switzerland: { emoji: "🇨🇭" },
  Syria: { emoji: "🇸🇾" },
  Tajikistan: { emoji: "🇹🇯" },
  Tanzania: { emoji: "🇹🇿" },
  Thailand: { emoji: "🇹🇭" },
  "Timor-Leste": { emoji: "🇹🇱" },
  Togo: { emoji: "🇹🇬" },
  Tonga: { emoji: "🇹🇴" },
  "Trinidad and Tobago": { emoji: "🇹🇹" },
  Tunisia: { emoji: "🇹🇳" },
  Turkey: { emoji: "🇹🇷" },
  Turkmenistan: { emoji: "🇹🇲" },
  Tuvalu: { emoji: "🇹🇻" },
  Uganda: { emoji: "🇺🇬" },
  Ukraine: { emoji: "🇺🇦" },
  "United Arab Emirates": { emoji: "🇦🇪" },
  "United Kingdom": { emoji: "🇬🇧" },
  "United States": { emoji: "🇺🇸" },
  Uruguay: { emoji: "🇺🇾" },
  Uzbekistan: { emoji: "🇺🇿" },
  Vanuatu: { emoji: "🇻🇺" },
  "Vatican City": { emoji: "🇻🇦" },
  Venezuela: { emoji: "🇻🇪" },
  Vietnam: { emoji: "🇻🇳" },
  Yemen: { emoji: "🇾🇪" },
  Zambia: { emoji: "🇿🇲" },
  Zimbabwe: { emoji: "🇿🇼" },
  Kosovo: { emoji: "🇽🇰" },
  Taiwan: { emoji: "🇹🇼" },
};

export default countryMeta;
